version: "3.1"

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    # restart: unless-stopped
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - mongo

  backend:
    container_name: backend
    build: ./backend
    restart: always
    ports:
      - "3500:3500"
    depends_on:
      - mongo

  frontend:
    container_name: frontend
    stdin_open: true
    build: .
    restart: on-failure
    ports:
      - "3000:3000"
  # cache:
  #   image: redis
  #   ports:
  #     - "6379:6379"
